name: Daily MCP Collect → Publish
on:
  schedule:
    - cron: '0 23 * * *'       # 每天 UTC 23:00
  workflow_dispatch:

env:
  HUGO_VERSION: '0.147.2'

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - name: Run collector
        env:
          GPT_API_KEY:  ${{ secrets.GPT_API_KEY }}
          GPT_API_URL:  ${{ secrets.GPT_API_URL }}
          GH_TOKEN:     ${{ secrets.GH_TOKEN }}
        run: python scripts/mcp_collect_and_publish.py
      - name: Commit generated posts
        run: |
          git config --global user.email "bot@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"
          git add content/ tracked_tools.json || true
          git commit -m "chore: daily MCP update $(date -u +'%F')" || echo "Nothing new"
          git push || echo "No changes"

  hugo:
    needs: collect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v3
        with: { hugo-version: ${{ env.HUGO_VERSION }} }
      - run: hugo --minify --baseURL "https://kk4099.github.io/mcp-blog"
      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public 